# ECE 196 – Python Packages Exercises
## Exercise 1 - Numpy

In [1]:
import numpy as np

1. Create a 10x10 matrix called ```board``` and fill it with a checkerboard pattern of 1 and 0 using Numpy.

In [2]:
board = np.zeros((10,10))
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


2. Write a NumPy program to sort an along the first, last axis of ```my_array```.

In [3]:
my_array = np.array([[4,6],[2,1]])
print(my_array)
print(np.sort(my_array, axis=0))
print(np.sort(my_array, axis=-1))

[[4 6]
 [2 1]]
[[2 1]
 [4 6]]
[[4 6]
 [1 2]]


3. 
a) Write a NumPy program to create an array named ```array``` with values ranging from 5 to 30.

In [4]:
array = np.arange(5,31)
print(array)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30]


b) Create a sub array ```array1``` that contains every third value starting at 7 and another sub array ```array2``` that contains every second value starting at 15.

In [5]:
array1 = array[2::3]
array2 = array[10::2]
print(array1)
print(array2)

[ 7 10 13 16 19 22 25 28]
[15 17 19 21 23 25 27 29]


c) Compare ```array1``` and ```array2``` using `> >= == <= <`.

In [6]:
print(array1 > array2)
print(array1 >= array2)
print(array1 == array2)
print(array1 <= array2)
print(array1 < array2)

[False False False False False False False False]
[False False False False False False False False]
[False False False False False False False False]
[ True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True]


d) Make ```array1``` a 4x2 matrix and ```array2``` a 2x4 matrix.

In [7]:
array1 = array1.reshape(4,2)
array2 = array2.reshape(2,4)
print(array1)
print(array2)

[[ 7 10]
 [13 16]
 [19 22]
 [25 28]]
[[15 17 19 21]
 [23 25 27 29]]


e)Try adding 2 to ```array1```.  
Now try multiplying ```array2``` by ```array3```.  
Can you add ```array1``` and ```array2```?  
Can you multiply ```array1``` and ```array2```?  
What happens when you try dot product on ```array1``` and ```array2```?

In [8]:
array3 = np.full((2, 4), 2)

array1 += 2
print(array1)

array2 *= array3
print(array2)

# array1 + array2    # broadcast error
# array1 * array2    # broadcast error
dot_product1 = np.dot(array2,array1)
dot_product2 = array1.dot(array2)
print(dot_product1)
print(dot_product2)

[[ 9 12]
 [15 18]
 [21 24]
 [27 30]]
[[30 34 42 42]
 [46 54 54 58]]
[[4812 3240]
 [6624 4560]]
[[ 822  954 1026 1074]
 [1278 1482 1602 1674]
 [2364 2724 3060 3156]
 [3000 3456 3888 4008]]
