# Numpy

<div class="alert alert-success">
<a href="https://numpy.org/doc/stable/user/whatisnumpy.html" class="alert-link">Numpy</a> is a Python library for scientific computing in Python, that provides a multidimensional array object and tools to working with these arrays efficiently. NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.
</div>

Read the <a href="https://numpy.org/devdocs/user/absolute_beginners.html">beginner's guide on Numpy</a> and more about its detailed <a href="https://numpy.org/doc/stable/reference/">documentation</a>.


1. Numpy vs list
2. Creating Numpy arrays
3. Shape
    * array shape
    * reshape
    * transpose
4. Indexing and slicing
5. Basic Numpy array operations

### 1. Numpy vs list
* **Size** - Numpy data structures take up less space
* **Performance** - faster than lists
* **Functionality** - Numpy have optimized functions such as linear algebra operations built in.

The elements in a NumPy array are all required to be of the same data type (homogeneous).  
Numpy arrays have specific <a href="https://numpy.org/devdocs/user/basics.types.html">numpy datatypes</a>.  
Numpy has operations that typically require nested loops in a simple list e.g. element wise operation is not possible on the list.

In [1]:
import numpy as np

my_list = [[1, 2 ,3], [4, 5, 6], [7, 8, 9]]
my_array = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
print(my_array)
print(my_list)

my_list[0][1] = 'a string'                       # list elements can be any type -- heterogeneous
# my_array[0][1] = 'a string'                    # numpy array elements must be the same type -- homogeneous
my_array2 = np.array([1, 2], dtype=np.float64)   # Specify a particular datatype
my_array3 = my_array2.astype(np.int64)
my_list2 = [float(i) for i in range(2)]          # Need list comprehension to type cast all elements
# my_list2 += 2

my_list2 = [num + 2 for num in my_list2]
print(my_list2)
my_array2 += 5
print(my_array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[2.0, 3.0]
[6. 7.]


### 2. Creating Numpy arrays
There are several different ways to create numpy arrays, to name a few:

In [2]:
# a = np.zeros((2,2))            # Create an array of all zeros with specified shape
# print(a)
# b = np.ones((1,2))             # Create an array of all ones with specified shape
# print(b)
# c = np.full((2,2), 7)          # Create an array filled with specified value(s)
# print(c)
# d = np.eye(2)                  # Create an identity matrix with specified shape
# print(d)
# e = np.random.random((2,2))    # Create an array filled with random values with specified shape
# print(e)
# f = np.empty((3,2))            # Create an array filled with random values depending on the state of your machine
# print(f)
# g = np.arange(2,12,2)          # Create a 1-D array from 0 to specified value (similar to Python's built-in range)
# print(g)                       # Also follows (start, stop, step)
# my_list = range(2, 20, 3)
# h = np.array(my_list)          # Create a numpy array from a list
# print(h)
i = np.linspace(0, 100, num=9) # Create a array evenly spaced by specified intervals
print(i)

[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]


### 3. Shape
You can use `array.ndim`, `array.size`, and `array.shape` to evaluate the shape of your numpy array.  
You are also able to freely manipulate the shape of your array using `array.reshape(row, col)` and `array.T`.
The shape of an array is a tuple of integers giving the size of the array along each dimension.  

In [3]:
array = np.arange(8).reshape(2, 2, 2)
print(array)
print('rows and columns and channels of array = ', array.shape)
array = np.reshape(array, (-1, 2))
print(array)
print('rows and columns and channels of array = ', array.shape)
array = array.T
print(array)
array = np.transpose(array)
print(array)
print(array.ndim)
print(array.size)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
rows and columns and channels of array =  (2, 2, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
rows and columns and channels of array =  (4, 2)
[[0 2 4 6]
 [1 3 5 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
2
8


### 4. Indexing and slicing
A new possible syntax for indexing. `[row][col] & [row,col]`  
Slicing still follows `start:stop:step`

In [4]:
my_list = [[1,1,2], [5,4,3]]
print(my_list)
# print(my_list[1,1])
my_array = np.array(my_list)
print(my_array[1][1])
print(my_array[1,1])
sub_array = my_array[:,::2]
print(sub_array)

[[1, 1, 2], [5, 4, 3]]
4
4
[[1 2]
 [5 3]]


What will the following sliced array print?

In [5]:
array = np.arange(24).reshape((6,4))
print(array)
sliced_array = array[1::2, :-2:3]
print(sliced_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 4]
 [12]
 [20]]


A)
```python
[[ 0]
 [ 5]
 [10]
 [15]]
```
B)  
```python
[[ 4]
 [12]
 [20]]
```
C)  
```python
[[ 5  7
 [13 15]]
 ```
D)  
```python
[[12 13 14 15]]
```

### 5. Basic Numpy array operations
Numpy allows for easier <a href="https://numpy.org/doc/stable/reference/routines.math.html" class="alert-link">mathematical operations</a>.
Some operations are overloaded as both operators and functions. Say x and y are both numpy arrays, we can perform the following:
```python
x + y == np.add(x, y)
x - y == np.subtract(x, y)
x / y == np.divide(x, y)
x * y == np.multiply(x, y)
x.dot(y) == np.dot(x, y)
np.sqrt(x)
np.square(x)
```
Numpy broadcasting lets us to perform operations on arrays of different sizes. Read more on <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">broadcasting documentation</a>.  
A lot of these operations have the option to specify the axis, read more about <a href="https://www.sharpsightlabs.com/blog/numpy-axes-explained/#:~:text=In%20any%20Python%20sequence%20%E2%80%93%20like,1%2C%E2%80%9D%20and%20so%20on.">Numpy axes</a>.

<center><img src="../media/dot_product.png" width="500px"></center>

In [6]:
my_list = [[1,2],[3,4]]
print(my_list)
my_list2 = [[4,3],[2,1]]
print(my_list2)
print(my_list+my_list2)

[[1, 2], [3, 4]]
[[4, 3], [2, 1]]
[[1, 2], [3, 4], [4, 3], [2, 1]]


In [7]:
my_array = np.array(my_list)
print(my_array)
my_array2 = np.array(my_list2)
print(my_array2)
print(my_array + my_array2) # supports broadcasting

[[1 2]
 [3 4]]
[[4 3]
 [2 1]]
[[5 5]
 [5 5]]


In [8]:
# print(my_list * my_list2)             # cannot operate on list
print(my_array * my_array2)             # easily perform element-wise product
print(np.multiply(my_array, my_array2)) # overloaded function to do the same thing
print(my_array2.dot(my_array))          # use this for matrix multiplication
print(np.dot(my_array, my_array2))      # another overloaded function
print(my_array.dot(my_array2))          # order matters for dot product!

[[4 6]
 [6 4]]
[[4 6]
 [6 4]]
[[13 20]
 [ 5  8]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]


<a href="https://numpy.org/doc/stable/reference/generated/numpy.sum.html">sum</a>  
`numpy.sum()` adds up all the values in your array or in a specified direction of your array.

In [9]:
my_array = np.array([[4,1],[3,2]])
print(my_array)

print(np.sum(my_array))
print(np.sum(my_array, axis=0))
print(np.sum(my_array, axis=1))

[[4 1]
 [3 2]]
10
[7 3]
[5 5]


<a href = "https://numpy.org/doc/stable/reference/generated/numpy.sort.html">sort</a>  
`numpy.sort()` sorts all values in your array or in a specified direction of your array.

In [10]:
my_array = np.array([[4,1],[3,2]])
print(my_array)

print(np.sort(my_array))               # sort along the last axis
print(np.sort(my_array, axis=None))    # sort the flattened array
print(np.sort(my_array, axis=0))       # sort along the first axis
print(np.sort(my_array, axis=1))       # sort along the second axis

[[4 1]
 [3 2]]
[[1 4]
 [2 3]]
[1 2 3 4]
[[3 1]
 [4 2]]
[[1 4]
 [2 3]]


<a href = "https://numpy.org/doc/stable/reference/generated/numpy.unique.html">unique</a>  
`numpy.unique()` finds the unique values in your array and return them in a sorted array

In [11]:
my_array = np.array([[0,1,0,2],[2,1,2,2],[0,1,2,3]])
print(my_array)

print(np.unique(my_array))
print(np.unique(my_array, axis=0))                 # returns the unique rows of the array
arr, ind = np.unique(my_array, return_index=True)  # returns unique values and the first index of the unique value
print(arr, ind)

[[0 1 0 2]
 [2 1 2 2]
 [0 1 2 3]]
[0 1 2 3]
[[0 1 0 2]
 [0 1 2 3]
 [2 1 2 2]]
[0 1 2 3] [ 0  1  3 11]


<a href = "https://numpy.org/doc/stable/reference/generated/numpy.amax.html">amax</a> & <a href = "https://numpy.org/doc/stable/reference/generated/numpy.amin.html">amin</a>  
<a href = "https://numpy.org/doc/stable/reference/generated/numpy.argmax.html">argmax</a> & <a href = "https://numpy.org/doc/stable/reference/generated/numpy.argmin.html">argmin</a>  
`numpy.amax()` and `numpy.amin()` find the first max and min value in your array.  
`numpy.argmax()` and `numpy.argmin()` find the index of the first max and min value in your array.  

In [12]:
my_array = np.array([[4, 2, 3],[1, 3, 1]])
print(my_array)

print(np.amax(my_array))             # Maximum of the flattened array
print(np.amax(my_array, axis=0))     # Maxima along the first axis
print(np.amax(my_array, axis=1))     # Maxima along the second axis

print(np.argmin(my_array))           # Index of the minimum of the flattened array
print(np.argmin(my_array, axis=0))   # Index of the minima along the first axis
print(np.argmin(my_array, axis=1))   # Index of the minima along the second axis

[[4 2 3]
 [1 3 1]]
4
[4 3 3]
[4 3]
3
[1 0 1]
[1 0]


<a href = "https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html">flatten</a> & <a href ="https://numpy.org/doc/stable/reference/generated/numpy.ravel.html#numpy.ravel">ravel</a>  
`numpy.ndarray.flatten` returns a copy of the array flattened into a 1D array.  
`numpy.ravel` returns a contiguous flattened 1D array.  
The difference is that `flatten` **makes a copy** of the original array, so modifying flattened array doesn't change the original array.

In [13]:
my_array = np.array([[4, 2, 3],[1, 3, 1]])
print(my_array)

a = my_array.flatten()
b = np.ravel(my_array)
print(a)               # prints a 1D flattened array
print(b)               # prints a 1D flattened array

a[0] = 0
print(a)               # flattened array is modified
print(my_array)        # original array is not modified

b[0] = 0
print(b)               # flattened array is modified
print(my_array)        # original array is also modified

[[4 2 3]
 [1 3 1]]
[4 2 3 1 3 1]
[4 2 3 1 3 1]
[0 2 3 1 3 1]
[[4 2 3]
 [1 3 1]]
[0 2 3 1 3 1]
[[0 2 3]
 [1 3 1]]
